export const reviewsData = {
  reviews: [
    {
      name: "Aji B",
      location: null,
      friends: null,
      reviews: 12,
      photos: 12,
      date: "10 months ago",
      text: "Amazing job! Ehab and his team did was awesome, prompt, and professional. They began June 8th and finished June 21st. I highly recommend this company for your kitchen remodel. They don't disappoint.",
      text_es:
        "¡Trabajo increíble! Ehab y su equipo fueron geniales, rápidos y profesionales. Comenzaron el 8 de junio y terminaron el 21 de junio. Recomiendo ampliamente esta empresa para la remodelación de su cocina. No decepcionan.",
      photos_count: 0,
      photo_captions: [],
      owner_response: "Thank you for the nice words. Glad to know that you are happy with our services.",
      owner_response_es:
        "Gracias por las amables palabras. Me alegra saber que está satisfecho con nuestros servicios.",
    },
    {
      name: "Muhumed Tagouri",
      location: null,
      friends: null,
      reviews: 1,
      photos: 0,
      date: "11 months ago",
      text: "Ehab, the owner, was professional, responsive, and detail-oriented throughout the entire process. The cabinets and countertops they installed are top-quality, and the project stayed on schedule.",
      text_es:
        "Ehab, el propietario, fue profesional, receptivo y minucioso durante todo el proceso. Los gabinetes y encimeras que instalaron son de la mejor calidad, y el proyecto se mantuvo según lo programado.",
      photos_count: 0,
      photo_captions: [],
      owner_response: null,
      owner_response_es: null,
    },
    {
      name: "Muad Nashnoush",
      location: null,
      friends: null,
      reviews: 9,
      photos: 0,
      date: "11 months ago",
      text: "amazing store and great customer service",
      text_es: "tienda increíble y excelente servicio al cliente",
      photos_count: 0,
      photo_captions: [],
      owner_response: null,
      owner_response_es: null,
    },
    {
      name: "Sai S",
      location: null,
      friends: null,
      reviews: 23,
      photos: 10,
      date: "6 months ago",
      text: "Trustworthy and reliable! The cabinets were good quality. We had issues with our contractor, who installed our cabinets poorly and mutilated our sink base cabinet and vent cabinet. The owner of Creative Kitchens, Ehab, personally helped us … More",
      text_es:
        "¡Confiable y fiable! Los gabinetes eran de buena calidad. Tuvimos problemas con nuestro contratista, quien instaló mal nuestros gabinetes y mutiló nuestro gabinete base del fregadero y gabinete de ventilación. El propietario de Creative Kitchens, Ehab, nos ayudó personalmente... Más",
      photos_count: 0,
      photo_captions: [],
      owner_response: "Thank you so much for the nice words. It was a pleasure doing business with you.",
      owner_response_es: "Muchas gracias por las amables palabras. Fue un placer hacer negocios con usted.",
    },
    {
      name: "Amal Hejazi",
      location: null,
      friends: null,
      reviews: 118,
      photos: 196,
      date: "5 months ago",
      text: "Ten years ago, I remodeled my kitchen, and I still experience top-notch quality, exceptional service, and outstanding management from this company. I wholeheartedly recommend their services—they truly are the best!",
      text_es:
        "Hace diez años, remodelé mi cocina, y todavía experimento calidad de primera, servicio excepcional y gestión sobresaliente de esta empresa. ¡Recomiendo de todo corazón sus servicios, realmente son los mejores!",
      photos_count: 0,
      photo_captions: [],
      owner_response: null,
      owner_response_es: null,
    },
    {
      name: "Cynthia Ellis",
      location: null,
      friends: null,
      reviews: 7,
      photos: 0,
      date: "5 months ago",
      text: "Great quality, good price, responsive service, and the work is done professionally, with joy and a smile! My go to team for my next project!!!",
      text_es:
        "Gran calidad, buen precio, servicio receptivo, y el trabajo se realiza profesionalmente, ¡con alegría y una sonrisa! ¡¡¡Mi equipo de confianza para mi próximo proyecto!!!",
      photos_count: 0,
      photo_captions: [],
      owner_response: "Thank you Centhia Ellis.",
      owner_response_es: "Gracias Centhia Ellis.",
    },
    {
      name: "J W",
      location: null,
      friends: null,
      reviews: 8,
      photos: 0,
      date: "a year ago",
      text: "I've been a customer for 8 years and I can't say anything bad. The products and services are great!",
      text_es: "He sido cliente durante 8 años y no puedo decir nada malo. ¡Los productos y servicios son excelentes!",
      photos_count: 0,
      photo_captions: [],
      owner_response: "Thank you for doing business with Creative Kitchens. We appreciate your great review.",
      owner_response_es: "Gracias por hacer negocios con Creative Kitchens. Agradecemos su excelente reseña.",
    },
    {
      name: "Rahmat Ahsani",
      location: null,
      friends: null,
      reviews: 1,
      photos: 0,
      date: "a year ago",
      text: "Reasonable and fair pricing. Strongly cooperative and honest with customers. Satisfactory after-sale services",
      text_es:
        "Precios razonables y justos. Altamente cooperativos y honestos con los clientes. Servicios posventa satisfactorios",
      photos_count: 0,
      photo_captions: [],
      owner_response: null,
      owner_response_es: null,
    },
    {
      name: "David Figueroa",
      location: null,
      friends: null,
      reviews: 2,
      photos: 0,
      date: "a year ago",
      text: "Very good attention and very good cabinets.",
      text_es: "Muy buena atención y muy buenos gabinetes.",
      photos_count: 0,
      photo_captions: [],
      owner_response: "Thank you for trusting Creative Kitchens. We appreciate your nice comment.",
      owner_response_es: "Gracias por confiar en Creative Kitchens. Agradecemos su amable comentario.",
    },
    {
      name: "Ruben L.",
      location: "Orlando, FL",
      friends: 0,
      reviews: 1,
      photos: 0,
      date: "Nov 1, 2021",
      text: 'My wife and I are extremely happy with the whole experience. The level of professionalism shown from the beginning having our interest as a family as the only priority is the most gratifying experience we have ever had. When we tried to explain what we wanted to accomplish, Doug stepped in with his expertise. He helped us accomplish all that we wanted and saved us money with a great design. He kept us well informed throughout the process. Delays due to COVID and the "supply chain" issues were dealt with promptly. We are looking forward to our next home upgrade. We are not just happy with the quality of work and professionalism, we are also grateful for the optimization of our resources that resulted in an optimum house value increase and a very happy family! We highly recommend Creative kitchen Designs and the team of professionals making it happen! Thank you, Doug!',
      text_es:
        'Mi esposa y yo estamos extremadamente felices con toda la experiencia. El nivel de profesionalismo mostrado desde el principio, teniendo nuestro interés como familia como la única prioridad, es la experiencia más gratificante que hemos tenido. Cuando tratamos de explicar lo que queríamos lograr, Doug intervino con su experiencia. Nos ayudó a lograr todo lo que queríamos y nos ahorró dinero con un gran diseño. Nos mantuvo bien informados durante todo el proceso. Los retrasos debido al COVID y los problemas de "cadena de suministro" se trataron con prontitud. Estamos esperando nuestra próxima mejora del hogar. ¡No solo estamos felices con la calidad del trabajo y el profesionalismo, también estamos agradecidos por la optimización de nuestros recursos que resultó en un aumento óptimo del valor de la casa y una familia muy feliz! ¡Recomendamos ampliamente Creative Kitchen Designs y el equipo de profesionales que lo hacen posible! ¡Gracias, Doug!',
      photos_count: 0,
      photo_captions: [],
      owner_response: null,
      owner_response_es: null,
    },
    {
      name: "Melina G.",
      location: "New York, NY",
      friends: 0,
      reviews: 2,
      photos: 0,
      date: "Sep 17, 2018",
      text: "I have to say that my kitchen is a dream come true everything from the cabinets to the countertops and the hardware. Thank you Louie for helping me what a pleasure. He is courteous, knowledgeable and always available to help. Everyone loves my kitchen!!! It is beautiful thank you Louie. Melina G Bayside NY",
      text_es:
        "Tengo que decir que mi cocina es un sueño hecho realidad, desde los gabinetes hasta las encimeras y los accesorios. Gracias Louie por ayudarme, qué placer. Es cortés, conocedor y siempre está disponible para ayudar. ¡¡¡A todos les encanta mi cocina!!! Es hermosa, gracias Louie. Melina G Bayside NY",
      photos_count: 0,
      photo_captions: [],
      owner_response: null,
      owner_response_es: null,
    },
  ],
  businessInfo: {
    owner_name: "Ehab",
    business_name: "Creative Kitchens",
    business_name_es: "Cocinas Creativas",
  },
}

import { reviewsData as reviews } from "@/data/reviews-data"

// Convert the reviews data to the format expected by the testimonials components
export const testimonials = reviews.reviews.slice(0, 5).map((review) => ({
  name: review.name,
  title: review.location || "Verified Customer",
  heading: review.text.split(".")[0] + ".",
  text: review.text,
  imageUrl: `/placeholder.svg?height=50&width=50&text=${review.name.charAt(0)}`,
}))
